### ISSUE TITLE
Download link of SEGUE failed

### ISSUE THREAD

**Issue by zoelir729** [kschan0214/sepia#12]
Failed to open the link of SEGUE: https://xip.uclb.com/i/software/SEGUE.html

**Comment by kschan0214** [comment]
Hi, 

The link still works fine for me. You should be able to see the following page after clicking the hyperlink:
![Screenshot 2020-11-27 at 16 34 49](https://user-images.githubusercontent.com/39571502/100464853-9c620d80-30ce-11eb-8c0f-374e114e9e15.png)

If it is not working for you, maybe you should try with other browsers or check your firewall setting.

Best,

Kwok

**Comment by zoelir729** [comment]
Thanks a lot! 
I indeed found some problems with my firewall setting.
And I have another question about downloading these toolboxes.
I have sent 3 emails to STI.Suite.MRI@gmail.com (https://people.eecs.berkeley.edu/~chunlei.liu/software.html) few days ago and failed to receive email in reply. I want to know if we can obtain the download link of STI suite in general, and the waiting time (one week or two?) ?
We would appreciate if you could provide some advices.

**Comment by kschan0214** [comment]
We received several feedbacks regarding a similar issue with STI Suite. 

SEPIA can work independently without having STI Suite. You can just leave the `STISuite_HOME` variable in 'SpecifyToolboxesDirectory.m' as an empty variable (i.e. `STISuite_HOME = []`). You will receive a warning message about missing the STI Suite toolbox and its related methods cannot be used, but other methods supported by SEPIA should not be affected. 

If you wish to use the STI Suite methods and they still haven't replied to your message, you can send me an email (k.chan@donders.ru.nl).

Hope this could be helpful. If there is no more question, I will close the issue for now. You can always start a new issue if you have more question. :)

Kwok

**Comment by zoelir729** [comment]
Thank you for your reply. 
It helps me a lot.
I have no more question. You can close the issue.
Again, thanks a lot!
