### ISSUE TITLE
compatibility issue with the new update of FANSI toolbox

### ISSUE THREAD

**Issue by zashams** [kschan0214/sepia#13]
Hi Kwok-Shing,

There's a function `dipole_kernel_fansi` in the FANSI toolbox that has been recently modified and is no longer compatible with the way used in the [code](https://github.com/kschan0214/sepia/blob/25c9940b995f7f8ed6959b347c7342a03d80f31f/misc/qsm_algorithm/FANSI/FANSI_4sepia.m#L39).
You can fix it by just removing the last argument (B0_dir) :)

Zahra

**Comment by kschan0214** [comment]
Hi Zahra,

Thanks for your report! 

Carlos mentioned that there are few changes in FANSI v2.0 (commit d97a20b1 and onwards). At the moment SEPIA v0.8.0 and v0.8.1 should run without problem with FANSI commit [dc68c306](https://gitlab.com/cmilovic/FANSI-toolbox/-/tree/dc68c306216871e1bb322303b4e3393fb0c1f770). 

FANSI v2.0 will be supported in the next major update of SEPIA (v1.0). :)

Many thanks!

Kwok
