### ISSUE TITLE
output not unwrapped 

### ISSUE THREAD

**Issue by romainviard** [kschan0214/sepia#21]
Great job, SEPIA is well designed, and would be very useful for those who want to come to QSM by customizing their pipeline. Then the documentation with exercices etc..is very interesting.

Yet I tried to reproduce result obtained using MEDI+ with MEDI+ in SEPIA ....but unfortunaltelly I'm far to succeed...so I tired step by step..beginning by phase unwrapping....And I'm wondering why the saved  "unwarped_echo_phase" is absolutely identical to the initial phase....(or could be just inverted when "invert phase data" is checked) ...

Did someone verify the unwrapped echo phase output  ? thank in advance,

**Comment by kschan0214** [comment]
Hi,

As the name suggested, the multi-echo phase should be unwrapped in the unwrapped_echo_phase image. I believe there could be some error occurred during the phase unwrapping process. 

To better understanding the issue, would you mind providing me the following information:
- SEPIA version used
- what is the unit of your input phase data? in DICOM value or in radian?
- can you attach a snapshot of the unwrapped echo phase data?
- is there any phase wrapping in the output 'total_field'?
- can you attach a copy of the sepia_config.m file?
- can you attach a copy of the output .log file?

Kwok

**Comment by ci2c** [comment]
Big Thanks for your kick reply...after cleanning up my MATLAB path, and my project, i did not reproduce the issue. 
Romain

**Comment by kschan0214** [comment]
Good to hear that! I'll close the issue for you.
