### ISSUE TITLE
Sepia  GUI malnfunction (?)

### ISSUE THREAD

**Issue by DimitriosGk** [kschan0214/sepia#3]
Hello,

I have started using SEPIA GUI for susceptibility mapping. I noticed that when I choose for example Region Growing and LVB, in matlab command window I see:
---The following unwrapping method is being used: Laplacian
---The resulting field map with the following unit: Hz
---Computing weighting map...Done!
---Saving unwrapped field map...done!
---Step 2: Recovering local field...
---The following method is being used: LBV

If i runt it a couple of times without any change, I get at some point my selections printed. Is it something that occurs to other users? 
Maybe a re-install would solve it?

I will make sure to update, thanks in advance for any hint.

**Comment by kschan0214** [comment]
Hi,

Sorry for the late reply as I was away for holidays.

The unwrapping step was designed such that when anything goes wrong with the selected algorithm, it will use the Laplacian method immediately. However, it also makes the debugging work difficult as the error message is kept. 

There could be several reasons why the region growing algorithm doesn't work. For example, missing code (but I don't think is your case as you should already have the MEDI toolbox), the region growing library is not supported in the Matlab version that you use, running out of memory when running the region growing method, etc. 

Could you try the following recommendations and let me know the output of them:
1) Use 'Graphcut', 'Laplacian STI suite', or 'SEGUE' (if you are using the current SEPIA master version) for the unwrapping to see if it still goes back to the 'Laplacian'?
2) What is the SEPIA version you are using?
3) What is the Matlab version you are using to run SEPIA?
4) What is the operating system you are using to run Matlab?
5) Are you using the recommended toolbox version as stated in (https://sepia-documentation.readthedocs.io/en/latest/getting_started/Installation.html)?

If you can share your one set of data (just the phase nifti file, the MAT header file and the sepia_log.m file are enough) with me (k.chan@donders.ru.nl) I can try to re-create the problem and get back to you with a more specific answer. 

Hope this could help.

Kwok

**Comment by DimitriosGk** [comment]
Hello ,


Thank you for the thorough reply, apologies for the late answer.

I had moved on with this issue, that is why it took long to see your email.


I was running on MATLAB 2018b, Linux Ubuntu. The SEPIA is running ok, it was my failure to read the notes and I was trying the wrong methods combination.

Another problem was the fact that I used another version of the STI package, as it is not available for downloading for now and apparently this caused of course

some problems as well.


I have modified the code of the GUI and SEPIA accordingly in a couple of spots and now it works well.

Thanks a log again for your answer!


Kind regards,


Dimitrios G. Gkotsoulias
Max Planck Institute
Leipzig, Germany
________________________________

**Comment by kschan0214** [comment]
Grad to hear that!

As far as I remember, there are some discrepancies of the input variables of some functions between different STI suite versions. The STI Suite developing team seems not very responsive recently. If you need STI Suite version 3, PM me and I can send you a copy. 

I'll close the issue if there is no further question. :)

Kwok

**Comment by DimitriosGk** [comment]
Thanks a lot for that!

I managed to get STI Suite v.3? eventually as well. Of course, you can close the issue :)


?est regards,

Dimitri?

________________________________
