### ISSUE TITLE
How to process a batch job in getting header info?

### ISSUE THREAD

**Issue by zoelir729** [kschan0214/sepia#34]
Hi Kwok,

I'm trying to process a batch job using Sepia with single echo 3T data.
And I want know how to process a batch job in getting header info like running SEPIA function with edited config file?

Looking forward to hearing from you!

Best,
Zoe

**Comment by zoelir729** [comment]
I worked it out according to the save_sepia_header.m file.
Thanks anyway.

**Comment by kschan0214** [comment]
Hi Zoe,

Good that you find the solution! Please feel free to also use the Discussion page (https://github.com/kschan0214/sepia/discussions) if you have any further questions about the usage of SEPIA :) 

Kwok
