### ISSUE TITLE
SEPIA results != STISuite results

### ISSUE THREAD

**Issue by DimitriosGk** [kschan0214/sepia#4]
Hello!

I have been using SEPIA and STISuite 3.0. 
I produced tissue phase images of the same sample using 1. SEPIA (Laplacian STISuite and VSHARP_STISuite) and 2.The same template functions in STISuite 3.0 by running them in a matlab script. Apparently, I get  different results in terms of contrast in the tissue phase (of course, I checked that SEPIA uses the same functions by checking the logs and to be sure I even run it step by step in matlab).
Any idea why this is happening? I will dig in a little bit more when I have the time.
An example of my results is below (STI suite template functions results to the left and SEPIA results using STISuite function to the right):
![sti](https://user-images.githubusercontent.com/29710018/67469182-20380380-f64c-11e9-99cd-f68b06c9bd5a.png)

Best regards,
DImitri

**Comment by kschan0214** [comment]
Hi Dimitri,

I haven't done a thorough comparison between the SEPIA pipeline and STI Suite one. I'll do a complete comparison between the two after the ISMRM deadline :).

My guess is the difference in the brain mask being used in the QSM processing, as you can see the strong susceptibility sources in the right are masked in the left (and subsequently became zero). The definition of ROI (i.e. brain mask) can have substantial impact on the final QSM map. If you have time, you can run the QSM process in separated steps in SEPIA, using the same brain mask as in the STI suite pipeline to start with, and compare the resulting map and output mask in each step. This should give you some ideas of why they produce different results.

Kwok

**Comment by DimitriosGk** [comment]
Hello :)

Thanks for your answer.
I have done  -in rush-  this comparison, using the same mask for both SEPIA and STI in 3 or 4 sample volumes. The change -as expected- happens on the background field removal step. There, using the V-SHARP method as implemented in STI, I get more contrast when using the STISuite.
About the masking, STISuite uses an eroded version of the given mask, that is the reason i suppose that we have these 'holes' on the QSM/Backround field removal results.
My aim initially, was to automate the process (for multiple volumes) using the STISuite, and on the way there i compared the results with SEPIA.
Both of them seem to perform fine, it is just weird how the two processes have contrast differences, while they are supposed to use the same functions.
But lets let the ISMRM deadline pass and we can make a more thorough comparison on some samples and validate that there is an issue first.

Best,
Dimitri

**Comment by DimitriosGk** [comment]
Hello!

I found what was going wrong with the code and I had these changes. It had to do with a wrong calculated mask that was adding random weights as it was getting numerically 'destroyed' by passing it from python to matlab most likely.
Fixed it and the results are the same.
So finally we can safely assume this is not a SEPIA issue and I am closing it.

Dimitri
