### ISSUE TITLE
Calling SEPIA commands without the use of the GUI

### ISSUE THREAD

**Issue by DimitriosGk** [kschan0214/sepia#47]

**Comment by jprfm** [comment]
Hi Dimitri,

one simple way to learn that is to open the config.m file that is written
on you output library after having used the GUI to run serious. The content
of that file is exactly what you would need to write on the command line.

For other options for the different algorithms, you can also refer to:
https://sepia-documentation.readthedocs.io/en/latest/method/Lookup-table-algorParam.html

Hope this helps,

José

**Comment by DimitriosGk** [comment]
Thanks a lot Jose!
I actually closed the topic before I saw the answer as I realised another fast solution, but your suggestion is excellent and saves effort!

All the best,
Dimitri
