### ISSUE TITLE
Bug in R2star_NLLS

### ISSUE THREAD

**Issue by loneblues** [kschan0214/sepia#48]
When you run SEPIA for R2 star mapping, when you use NLLS, you get an error that stats function 'Signal_mGRE' is missing. 
Obviously it appears that the function is present in the R2 star repository, but is missing from the SEPIA repository. 
Thanks.

**Comment by kschan0214** [comment]
Thank you for reporting the bug! The issue should now be resolved in the update v1.2.1.

Kwok
