### ISSUE TITLE
STI suite location

### ISSUE THREAD

**Issue by simon-mri** [kschan0214/sepia#67]
Hi Kwok + Jose', 

Just to let you know that STI suite has moved from 

https://people.eecs.berkeley.edu/~chunlei.liu/software.html 

to

https://chunleiliulab.github.io/software.html

for the SEPIA toolbox page  
https://sepia-documentation.readthedocs.io/en/latest/ aka
https://github.com/kschan0214/sepia.documentation/blob/master/docs/index.rst

Cheers, 

Simon

**Comment by kschan0214** [comment]
Hi Simon, thanks for the update! The link to STI Suite should now be working!

Kwok
