### ISSUE TITLE
spatial mismatch

### ISSUE THREAD

**Issue by lconcha** [kschan0214/sepia#82]
Hello.

I am trying to compute QSM on rodent data. Images were converted from paravision format using [brkraw](https://brkraw.github.io/).

After completion of the pipeline, some derived maps appear to be spatially discordant to the original magnitude image. It may seem like this is due to mask erosion, but it truly seems to be misaligned. Please see a snapshot of the magnitude image and sepia outputs, and notice how the Chi map seems to be shifted with respect to the magnitude image. The last panel in the figure shows sepia configuration used.

Am I doing anything wrong with how the maps are calculated? Your help is much appreciated!

![sepia_rat](https://github.com/kschan0214/sepia/assets/5749858/a18885fb-f8b1-47ca-a265-720c3bbb34e2)

**Comment by kschan0214** [comment]
Thanks for the update and good to hear the software is working fine!
