### ISSUE TITLE
ROMEO quality mask

### ISSUE THREAD

**Issue by bart-larsen** [kschan0214/sepia#89]
I was exploring different approaches to masking based on phase quality/reliability and noticed that using the option for quality mask with ROMEO produces the following error:

> masking option 'qualitymask 0.5' is undefined

For reference these are the options selected:
<img width="939" alt="image" src="https://github.com/user-attachments/assets/3614e566-3b63-40de-b47e-6970fe9cfb8d">

Not sure if this is a problem on my end or with SEPIA.

**Comment by kschan0214** [comment]
Hi, 

Sorry for the late follow-up! I believe this is a bug in the ROMEO.m function where unintended double quotation marks are used when the masking option (-k) is set with qualitymask and a threshold value in constructing the ROMEO command. This bug needed to be handled on the mritools side as this is the function provided by the tool.

In the meantime, you can try the following updated ROMEO.m function. It should (temporarily) fix the issue.
[ROMEO.m.zip](https://github.com/user-attachments/files/16912828/ROMEO.m.zip)

Hi, @korbinian90 is that possible for you to have a look at this issue and see if my proposed solution works (properly). :)

**Comment by korbinian90** [comment]
Hi, 

the temporary solution looks good to me. I added a fix for mritools for the next release v4.3.0

The problem is that "qualitymask 0.5" gets parsed as one argument instead of two. The new romeo cmd splits the argument in that case

**Comment by bart-larsen** [comment]
Thank you!
